CREATE TABLE IF NOT EXISTS `category_taxonomy` (
  `id` int AUTO_INCREMENT NOT NULL,
  `root_category` varchar(64) NOT NULL,
  `subcategory` varchar(128),
  `product_type` varchar(128),
  `use_case` varchar(128),
  `audience` varchar(128),
  `price_band` varchar(32),
  `region_relevance` varchar(64),
  CONSTRAINT `category_taxonomy_id` PRIMARY KEY(`id`)
);--> statement-breakpoint
INSERT INTO `category_taxonomy` (`root_category`, `subcategory`, `product_type`, `use_case`, `audience`, `price_band`, `region_relevance`) VALUES
('home', 'Kitchen', 'Gadgets', 'meal prep', 'home cooks', 'mid', 'US,UK,EU'),
('home', 'Kitchen', 'Storage', 'organization', 'home cooks', 'low', 'US,UK,EU'),
('home', 'Kitchen', 'Cookware', 'cooking', 'home cooks', 'mid', 'US,UK,EU'),
('home', 'Decor', 'Lighting', 'ambiance', 'homeowners', 'mid', 'US,UK,EU'),
('home', 'Decor', 'Wall art', 'styling', 'renters', 'low', 'US,UK,EU'),
('home', 'Garden', 'Tools', 'outdoor care', 'gardeners', 'mid', 'US,EU'),
('beauty', 'Skincare', 'Serums', 'anti-aging', 'adults 25-45', 'mid', 'US,UK,EU'),
('beauty', 'Skincare', 'Cleansers', 'daily routine', 'all adults', 'low', 'US,UK,EU'),
('beauty', 'Skincare', 'Moisturizers', 'hydration', 'all adults', 'mid', 'US,UK,EU'),
('beauty', 'Makeup', 'Eyes', 'daily look', 'women 18-35', 'low', 'US,UK,EU'),
('beauty', 'Makeup', 'Lips', 'color', 'women 18-35', 'low', 'US,UK,EU'),
('beauty', 'Hair', 'Styling tools', 'styling', 'women 18-45', 'mid', 'US,UK,EU'),
('electronics', 'Audio', 'Earbuds', 'commute', 'commuters', 'mid', 'US,UK,EU'),
('electronics', 'Audio', 'Speakers', 'home audio', 'tech enthusiasts', 'mid', 'US,UK,EU'),
('electronics', 'Mobile', 'Chargers', 'charging', 'mobile users', 'low', 'US,UK,EU'),
('electronics', 'Mobile', 'Cases', 'protection', 'mobile users', 'low', 'US,UK,EU'),
('electronics', 'Smart home', 'Lighting', 'automation', 'homeowners', 'mid', 'US,UK,EU'),
('pet', 'Dogs', 'Feeders', 'feeding', 'dog owners', 'mid', 'US,UK,EU'),
('pet', 'Dogs', 'Toys', 'play', 'dog owners', 'low', 'US,UK,EU'),
('pet', 'Dogs', 'Grooming', 'care', 'dog owners', 'mid', 'US,UK,EU'),
('pet', 'Cats', 'Toys', 'play', 'cat owners', 'low', 'US,UK,EU'),
('pet', 'Cats', 'Feeders', 'feeding', 'cat owners', 'mid', 'US,UK,EU'),
('pet', 'Aquarium', 'Accessories', 'tank care', 'aquarium owners', 'mid', 'US,EU'),
('fashion', 'Apparel', 'Activewear', 'workout', 'fitness enthusiasts', 'mid', 'US,UK,EU'),
('fashion', 'Apparel', 'Loungewear', 'comfort', 'adults 18-45', 'mid', 'US,UK,EU'),
('fashion', 'Accessories', 'Bags', 'daily carry', 'commuters', 'mid', 'US,UK,EU'),
('fashion', 'Accessories', 'Jewelry', 'styling', 'women 18-35', 'low', 'US,UK,EU'),
('fashion', 'Footwear', 'Sneakers', 'casual wear', 'streetwear fans', 'mid', 'US,UK,EU'),
('sports', 'Fitness', 'Yoga', 'home workout', 'yoga practitioners', 'low', 'US,UK,EU'),
('sports', 'Fitness', 'Resistance bands', 'strength', 'home gym users', 'low', 'US,UK,EU'),
('sports', 'Outdoor', 'Camping', 'weekend trips', 'outdoor enthusiasts', 'mid', 'US,EU'),
('sports', 'Outdoor', 'Hiking', 'trails', 'hikers', 'mid', 'US,EU'),
('toys', 'Kids', 'Educational', 'learning', 'parents', 'mid', 'US,UK,EU'),
('toys', 'Kids', 'Plush', 'comfort play', 'young children', 'low', 'US,UK,EU'),
('toys', 'Games', 'Puzzles', 'family night', 'families', 'low', 'US,UK,EU'),
('toys', 'Games', 'Board games', 'social play', 'teens and adults', 'mid', 'US,UK,EU'),
('automotive', 'Interior', 'Organizers', 'cabin storage', 'commuters', 'low', 'US,UK,EU'),
('automotive', 'Interior', 'Phone mounts', 'hands-free driving', 'drivers', 'low', 'US,UK,EU'),
('automotive', 'Safety', 'Dash cams', 'recording', 'drivers', 'mid', 'US,UK,EU'),
('automotive', 'Exterior', 'Care kits', 'detailing', 'car owners', 'mid', 'US,UK,EU');
